baseURL: https://www.marcwilliamspsychology.com
title: Dr Marc Williams, Clinical Psychologist
theme: gokarna
languageCode: en
defaultContentLanguage: en
enableEmoji: yes
enableRobotsTXT: yes
pygmentsStyle: monokai
params:
  AvatarAltText: avatar
  ShowBackToTopButton: yes
  avatarSize: size-m
  avatarURL: /images/profile.png
  customHeadHTML: "    <!-- KaTeX -->\r\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css\"
    integrity=\"sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC\"
    crossorigin=\"anonymous\">\r\n    <script defer src=\"https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js\"
    integrity=\"sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja\"
    crossorigin=\"anonymous\"></script>\r\n    <script defer src=\"https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js\"
    integrity=\"sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR\"
    crossorigin=\"anonymous\"></script>\r\n    <script>\r\n      document.addEventListener(\"DOMContentLoaded\",
    function() {\r\n        renderMathInElement(document.body, {\r\n          // customised
    options\r\n          // • auto-render specific keys, e.g.:\r\n          delimiters:
    [\r\n            {left: '$$', right: '$$', display: true},\r\n            {left:
    '$', right: '$', display: false},\r\n          ],\r\n          // • rendering
    keys, e.g.:\r\n          throwOnError : false\r\n        });\r\n      });\r\n
    \   </script>\r\n  "
  description: Hello - my name is Marc. I provide therapy and supervision, specialising in cognitive behaviour therapy (CBT) and compassion-focused therapy (CFT). I provide therapeutic support for a variety of difficulties, such as anxiety, low mood, and eating disorders. I also provide support to people experiencing climate- / eco-distress. I work with a diversity of clients from a range of backgrounds, and can provide therapy in English or in Welsh. If you would like to discuss potentially working together, you can contact me at m.owenwilliams@gmail.com.
  #footer: The Marauders
  metaKeywords:
    - blog
    - gokarna
    - hugo
  socialIcons:
    - name: twitter
      url: https://twitter.com/mowenwilliams
#    - name: linkedin
#      url: https://example.com
#    - name: stackoverflow
#      url: https://example.com
#    - name: dribbble
#      url: https://example.com
#    - name: instagram
#      url: https://example.com
#    - name: twitch
#      url: https://example.com
    - name: email
      url: mailto:m.owenwilliams@gmail.com
menu:
  main:
    - name: Home
      pre: <span data-feather='home'></span>
      url: /
      weight: 1
    - name: Publications
      pre: <span data-feather='book'></span>
      url: /publications/
      weight: 2
    - name: Privacy Policy
      pre: <span data-feather='lock'></span>
      url: /privacy-policy/
      weight: 3
#    - name: Tags
#      pre: <span data-feather='tag'></span>
#      url: /tags/
#      weight: 4
#    - identifier: github
#      pre: <span data-feather='github'></span>
#      url: https://github.com/526avijitgupta/gokarna
#      weight: 5
#    - identifier: buymeacoffee
#      pre: <span data-feather='coffee'></span>
#      url: https://www.buymeacoffee.com/avijitgupta
#      weight: 6
#    - identifier: rss
#      pre: <span data-feather='rss'></span>
#      url: /index.xml
#      weight: 7
markup:
  tableOfContents:
    endLevel: 4
    ordered: no
    startLevel: 1
